; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30145.0 

	TITLE	D:\Dev\Exodus\Third\zlib\zlib\contrib\vstudio\vc14\x86\TestZlibDebug\Tmp\inffast.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
